admin:
  user: admin.teste
  password: Jvs9^@B809lP
coordinator:
  user: gestor.teste
  password: Jvs9^@B809lP
instructor:
  user: instrutor.teste
  password: Jvs9^@B809lP
student:
  user: aluno.teste
  password: Jvs9^@B809lP
staff-member:
  user: colaborador.teste
  password: Jvs9^@B809lP
human-resources:
  user: gp.teste
  password: Jvs9^@B809lP

USER_LOGIN: admin.teste
USER_PSW: Jvs9^@B809lP


